### ISSUE TITLE
Recommended tool for expression data 

### ISSUE THREAD

**Issue by dfermin** [dgarrimar/sqtlseeker2-nf#4]
Do you have any recommendations for RNAseq analysis tools that work well with your tool?
I was considering using Salmon to get TPM values but I wasn't sure if there was another tool out there you know works well with sqtlseeker2.

**Comment by dgarrimar** [comment]
You can use sqtlseeker2-nf after any transcript quantification method. Of course, the quality of the results will depend on the quality of the transcript quantifications too, but there is no specific recommendation from our side
