### ISSUE TITLE
sQTL sharing analysis in paper

### ISSUE THREAD

**Issue by jdee3** [dgarrimar/sqtlseeker2-nf#6]
Hello,

Thank you for this publicly available resource!

I've been trying to recreate the sharing analysis in your paper (Identification and analysis of splicing quantitative trait loci across multiple tissues in the human genome), but it's not clear whether you implemented mashR or not. In the body of your paper, it states that mashR is not applicable, based on your approach. But in the Supp data, you refer to a "dendrogram obtained using mashR on LeafCutter sQTLs from GTEx V8", and you compare your sharing metrics to the mashR output. I can't seem to find your code for this specific mashR analysis; can you please share it? Thank you in advance!

**Comment by dgarrimar** [comment]
Hi,

we did not run mashR as it could not be applied in our scenario. In the Methods section we claim: "We [...] compare our trees with the one obtained using mashr[[30]](https://www.nature.com/articles/s41467-020-20578-2#ref-CR30) for LeafCutter sQTLs in GTEx V8[[12]](https://www.nature.com/articles/s41467-020-20578-2#ref-CR12), available at https://github.com/broadinstitute/gtex-v8." This refers to the sQTLs obtained by the GTEx Consortium in [12], not to our sQTLs.
